### ISSUE TITLE
Ajit Upadhyay

### ISSUE THREAD

**Issue by ajitup73** [ComputationalRadiationPhysics/picongpu-communitymap#1]
Dr. Ajit Upadhyay, 
Laser Plasma Section
Raja Ramanna Center for Advanced Technology, Indore, 452013, India.

Location:  22.6676,75.7899

-Individual user
-Trying to use it for particle acceleration simulation

**Comment by ax3l** [comment]
Thank you very much for the report and using PIConGPU! ✨ 
I added you to the map.

Can you verify I got the right spot? https://computationalradiationphysics.github.io/picongpu-communitymap/
