### ISSUE TITLE
entry to the users map

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu-communitymap#11]
*Hi, thank you for adding yourself to the PIConGPU community map!*

*Please provide the following information so we can add an entry:*

### Name & Info
Cristian Bontoiu
PhD Student

*How shall we list you and the group you work in?*

Cristian Bontoiu

*Are you representing a larger organization/collaboration/project where PIConGPU is regularly used in?*

No

*If you like, do not hesitate to share what you used PIConGPU for!*

I will use PIConGPU to investigate if electron bunches can be accelerated as they pass through carbon nanotubes using lasers to create wakes. This could be an alternative to beam acceleration in plasma.

### Location

Cockroft Institute/Liverpool University - Physics Department

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*
*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*

53.34444,-2.64128

- go to https://www.openstreetmap.org
- select your location
- right click -> "show address"
- copy link from address bar or coordinates shown on the left

**Comment by ax3l** [comment]
Hi Cristian,

thanks for opening an issue! We added you to the map in ab5e3f876991120bdf4ad6df91b56614178ffcee - welcome to the PIConGPU community! :sparkles:
