### ISSUE TITLE
picongpu-communitymap-Hao Peng

### ISSUE THREAD

**Issue by prlWanted** [ComputationalRadiationPhysics/picongpu-communitymap#12]
*Hi, thank you for adding yourself to the PIConGPU community map!*

*Please provide the following information so we can add an entry:*

### Name & Info

*How shall we list you and the group you work in?*
My name is Hao PENG, working as a post-doc at college of engineering physics , Shenzhen Technology University, which is located in Shenzhen China.

*Are you representing a larger organization/collaboration/project where PIConGPU is regularly used in?*
Yes, I am a member of our Thomson scattering. We are developing a thomson scatttering source with relativistic electron beams and intense laser.

*If you like, do not hesitate to share what you used PIConGPU for!*
I am going to use PIConGPU for the simulation of thomson scattering between lasers and relativistic electron beam.

### Location

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*
*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*

- go to https://www.openstreetmap.org
- select your location
- right click -> "show address"
- copy link from address bar or coordinates shown on the left

22.5379,114.0504

**Comment by ax3l** [comment]
Welcome to the PIConGPU community! :sparkles: 
Added in #13

**Comment by PrometheusPi** [comment]
@prlWanted Thanks for providing all the information. We added your institute the our community map. Welcome to PIConGPU!
