### ISSUE TITLE
eli np

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-communitymap#2]
*Hi, thank you for adding yourself to the PIConGPU community map!*

*Please provide the following information so we can add an entry:*

### Name & Info

*How shall we list you and the group you work in?*
Andrei Berceanu, ELI-NP

*Are you representing a larger organization/collaboration/project where PIConGPU is regularly used in?*
ELI-NP

*If you like, do not hesitate to share what you used PIConGPU for!*
I use PIConGPU for laser wakefield acceleration simulations.

### Location

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*
*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*
44.34984, 26.04994

**Comment by ax3l** [comment]
Thank you very much for using PIConGPU and the report!

I updated your entry in daf96a96e859075b6803f76d024ba3e179a1e8ac, can you confirm? :)
https://computationalradiationphysics.github.io/picongpu-communitymap/

**Comment by berceanu** [comment]
Yes, the details are correct :+1:
