### ISSUE TITLE
ajitup73

### ISSUE THREAD

**Issue by ajitup73** [ComputationalRadiationPhysics/picongpu-communitymap#3]
*Hi, thank you for adding yourself to the PIConGPU community map!*

*Please provide the following information so we can add an entry:*

### Name & Info
Dr. Ajit Upadhyay
Head, Plasma Simulation Activity,
Laser Plasma Division,
Raja Ramanna Centre for Advanced Technology,
Indore 452013, India

*How shall we list you and the group you work in?*

Our group work on Laser plasma interaction where we have 10TW, 150 TW fsec laser facilities and also adding a 1 PW laser facility within 2-3 months (installation is in progress).
http://www.cat.gov.in/

*Are you representing a larger organization/collaboration/project where PIConGPU is regularly used in?*
NO, I am the first user of PIConGPU

*If you like, do not hesitate to share what you used PIConGPU for!*
I plan to use it for LWFA and ion acceleration from laser-plasma interaction.

### Location

Indore, India
https://www.openstreetmap.org/search?whereami=1&query=22.6775%2C75.7903#map=15/22.6775/75.7903

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*
*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*

- go to https://www.openstreetmap.org
- select your location
- right click -> "show address"
- copy link from address bar or coordinates shown on the left

**Comment by ax3l** [comment]
Thanks a lot for the continued support! Updated in 9fd26d651d3d6cf7213bae14f5525e472039be34
