### ISSUE TITLE
Wenyin Wei

### ISSUE THREAD

**Issue by WenyinWei** [ComputationalRadiationPhysics/picongpu-communitymap#9]
### Name & Info
I am Wenyin Wei from Tsinghua University, China. Nice to discover PIConGPU as a powerful tool to simulate plasma. 

I am an individual researcher but would introduce PIC to my lab partners after I am familiar with it. 

Nice to see you all~

### Location
40.0018,116.3181
Tsinghua University, Beijing, China

**Comment by ax3l** [comment]
Hi Wenyin, welcome to PIConGPU!
We are glad you like it and participate in our community :sparkles: 

I added you in a1ee1fc4183ca8d41f546696c53221367c181939 to the map.
